### ISSUE TITLE
Configure integration of Heroku deployment with GitHub

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-l1storez#21]
It's a follow-up for #20.

* [x] Accept invitation to [this organization](https://github.com/kpi-web-guild)
  * optionally make your membership public (on [this page](https://github.com/orgs/kpi-web-guild/people?type=source)), so that there will be hat logo displayed on your profile page ^^
* [x] Choose [this repo](https://github.com/kpi-web-guild/django-girls-blog-l1storez) in `Heroku Dashboard` on `Deploy` page
* [ ] Make [`master` branch](https://github.com/kpi-web-guild/django-girls-blog-l1storez/tree/master) be deployed on update once the tests pass

**Comment by l1storez** [comment]
automatic deploy or manual?

**Comment by webknjaz** [comment]
auto

**Comment by l1storez** [comment]
I think I did

**Comment by l1storez** [comment]
Item could not be created:
Admin access to repository required

**Comment by webknjaz** [comment]
Okay, complete the rest of the checkboxes and close this then.

**Comment by webknjaz** [comment]
> Item could not be created:
> Admin access to repository required

Try again now.

**Comment by l1storez** [comment]
it's alive!

**Comment by webknjaz** [comment]
Did you finish the last checkbox?
