### ISSUE TITLE
Learn Git

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-l1storez#4]
![](https://i.pinimg.com/564x/25/73/14/257314878858202f4cf6b9ca37981cf0.jpg)

Please read&learn the following:

* [x] [ProGit 2](https://git-scm.com/book/en/v2) [:ukraine:](https://git-scm.com/book/uk/v2)
* [x] [Try Git](https://try.github.io/)
* [x] [Try Git Branching](http://learngitbranching.js.org/)
* [x] [Interactive diagram/cheatsheet about git](http://ndpsoftware.com/git-cheatsheet.html)
* [x] [You're using git wrong](https://web.archive.org/web/20181029051129/https://dpc.pw/blog/2017/08/youre-using-git-wrong/)
* [x] [Learn git concepts, not commands](https://dev.to/unseenwizzard/learn-git-concepts-not-commands-4gjc)
* [x] [The advantages of an email-driven git workflow](https://drewdevault.com/2018/07/02/Email-driven-git.html)
* [x] [Git For Ages 4 And Up](https://youtu.be/1ffBJ4sVUb4)

Extras:
* [x] [A useful template for commit messages](http://codeinthehole.com/tips/a-useful-template-for-commit-messages/)
* [x] [Understanding the GitHub Flow](https://guides.github.com/introduction/flow/)
* [x] [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)
* [x] [email + git = <3](https://git-send-email.io/)

**Comment by l1storez** [comment]
- [ ] 1 chapter
- [ ] 2 ch
- [ ] 3 ch
- [ ] 4 ch
- [ ] 5 ch
- [ ] 6 ch
- [ ] 7 ch
- [ ] 8 ch
- [ ] 9 ch
- [ ] 10 ch
- [ ]  a1
- [ ]  a2
- [ ]  a3
