### ISSUE TITLE
Create an empty commit on master (and push nothing else there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-l1storez#5]
```console
git commit --allow-empty -m 'Initial commit'
git push origin master
```

And report here after that.

**Comment by l1storez** [comment]
fatal: 'origin' does not appear to be a git repository

**Comment by webknjaz** [comment]
@l1storez

This probably means that you've created a local git repository with `git init` and didn't add a remote called `origin`. If you were to clone it from GitHub, the `origin` would point there by default.

There's instructions for these two cases right at the repo front page: https://github.com/kpi-web-guild/django-girls-blog-l1storez.

**Comment by l1storez** [comment]
Add a remote called origin, but authentication to origin master failed

**Comment by webknjaz** [comment]
Check that you've added your currently used SSH key to GitHub.

**Comment by webknjaz** [comment]
I've enabled branch protection for master. You won't be able to push there directly anymore. This part of the task has been completed.

The only mistake is that you've made 9 different commits, some of which modify README. The task was to create just one empty commit, not touching any files.
